export default {
    CONTRIBUTION_SOURCE:"source",
    CONTRIBUTION_TYPE:"rectype",
    NEWSLETTER:"newsletter",
    TITLE:"anrede",
    LANGUAGE:"",
    FIRSTNAME:"vorname",
    LASTNAME:"nachname",
    EMAIL:"email",
    ADDRESS:"street",
    CITY:"CITY",
    COUNTRY_ID:"CountryId",
    ZIP:"postcode",
    IBAN:"sl_iban",
    BIC:"sl_bic",
    AMOUNT:"abetrag",
    CONTRUBUTION_EXTERNAL_ID:"spende_id",
    DATE:"datum"
  }